# Generated by Django 5.1.7 on 2025-03-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_likes'),
        ('shop', '0008_product_discount_price_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='shop.product'),
        ),
    ]
